### ISSUE TITLE
להתחיל לעשות מנוע חיפוש ראשוני

### ISSUE THREAD

**Issue by rubenaz** [rubenaz/BatchSearching#4]
DuckDuckgo של  API-להתחיל לעשות מנוע חיפוש ראשוני זאת אומרת פשוט לעשות חיפוש ושהתוצאה תהיה תשובה מה

**Comment by asafbn** [comment]
תוסף עם כפתור שיש לו גישה לhtml לעמוד שהמשתמש גולש בו.
רמה 1: התוסף רואה את הurl 
רמה 2: התוסף קורא את הhtml של המשתמש

**Comment by asafbn** [comment]
תוסף עם כפתור שיש לו גישה לhtml לעמוד שהמשתמש גולש בו.
urlרמה 1: התוסף רואה את ה
 של המשתמש htmlרמה 2: התוסף קורא את ה
